### ISSUE TITLE
Impressed and in need of a little guidance

### ISSUE THREAD

**Issue by Charvine-300** [LordGhostX/lordghostx.github.io#1]
Hello, I’m a fellow student of the University of Lagos and have heard about you and how far you’ve come in the programming world. I need some advice because I’m not really sure what field of computer science I want to major in, I don’t want to go full stack 😂😂, so I was hoping maybe a few kind words would help me push forward. I’m currently starting a 2d game project in python because that’s the only language I can beat my chest and say I know well. Just a fellow programmer looking for some motivation 🖤

**Comment by LordGhostX** [comment]
Hi, I'm happy you're impressed and yes I can be of help if you're looking for who to have a conversation with on what path to take in tech. You can reach out to me on twitter - https://twitter.com/LordGhostX
